# Workflow for deploying Dynamic WebSite to InfityFree Host
name: Deploy MUNAP WebSite 

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
    
    - name: Configure FTP
      run: |
        echo "machine ftpupload.net" >> ~/.netrc
        echo "login if0_35105569" >> ~/.netrc
        echo "password SAZoEgJ127QbU" >> ~/.netrc
        chmod 600 ~/.netrc
    
    - name: Installer lftp
      run: |
        sudo apt-get update
        sudo apt-get install lftp -y
        
    - name: Deploy to InfinityFree
      run: |
        lftp -e "mirror -R -n -x .gitignore -x scss .github --delete-first ./ htdocs/" -d ftpupload.net  
